name: Generate Snake animation

on:
  schedule: # chạy tự động 1 lần/ngày
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Kettailor
          outputs: dist/snake.svg

      - name: Push to output branch
        uses: EndBug/add-and-commit@v9
        with:
          add: "dist/snake.svg"
          branch: output
          message: "Generate snake animation"
