name: Generate Snake animation

on:
  schedule:
    - cron: "0 0 * * *" # chạy 1 lần/ngày
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Kettailor
          outputs: dist/snake.svg

      - name: List generated files
        run: ls -R dist

      - name: Push to output branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          force: true
